language: php
sudo: false

cache:
  directories:
    node_modules
    vendor

matrix:
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'

install:
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib
  - source $DEV_LIB_PATH/travis.install.sh

script:
  - source bin/travis.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh
